name: CMake

on:
  push:
  create:
  #release:
  #  types: # This configuration does not affect the page_build event above
  #    - published

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #- uses: ilammy/setup-nasm@v1
      #with:
      #  from-source: false
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install nasm and genisoimage
        shell: bash
        run: sudo apt-get install -y nasm genisoimage libfl-dev grub2-common mtools build-essential wget make tar git cmake libmpc-dev libgmp3-dev libmpfr-dev

      - name: Cache sources
        id: compiler-src-cache
        uses: actions/cache@v3
        with:
          path: ~/build/cross/src
          key: ${{ runner.os }}-compiler-src

      - name: Download compiler
        if: steps.compiler-src-cache.outputs.cache-hit != 'true'
        shell: bash
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "ci"
          make download_toolchain download_autotools

      - name: Cache compiler
        id: compiler-cache
        uses: actions/cache@v3
        with:
          path: ~/opt
          key: ${{ runner.os }}-compiler-${{ hashFiles('utils/patches/*.patch') }}

      - name: Prepare compiler
        if: steps.compiler-cache.outputs.cache-hit != 'true'
        shell: bash
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "ci"
          make CORES=2 build_autotools patch do_autotools_thing build_cross

      - name: Build libr, libphobos, libd
        shell: bash
        run: |
          make CORES=2 install_libr build_libphobos install_libd

      - name: Build kernel, initrd, and everything
        shell: bash
        run: |
          CMAKE_BUILD_TYPE=RelWithDebInfo make CORES=2 build

      # save artifacts
      - name: Save entire kernel
        uses: actions/upload-artifact@v1
        with:
          name: kernel.elf
          path: ${{runner.workspace}}/build/bin/kernel

      - name: Save initrd
        uses: actions/upload-artifact@v1
        with:
          name: initrd
          path: ${{runner.workspace}}/build/initrd_file

      - name: Save boot image
        uses: actions/upload-artifact@v1
        with:
          name: kernel.iso
          path: ${{runner.workspace}}/build/rubiKernel.iso

      - name: Save grub image
        uses: actions/upload-artifact@v1
        with:
          name: grub.iso
          path: ${{runner.workspace}}/build/grub.iso

      # create release
      - name: Archive
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: |
          tar czvf kernel.tar.gz bin/kernel;
          tar czvf initrd_file.tar.gz initrd_file;
          tar czvf rubiKernel.iso.tar.gz rubiKernel.iso;
          tar czvf grub.iso.tar.gz grub.iso;
          ls -la ${{runner.workspace}}/build;
          mkdir -p ${{runner.workspace}}/rubi_kernel/build
          cp kernel.tar.gz initrd_file.tar.gz rubiKernel.iso.tar.gz grub.iso.tar.gz ${{runner.workspace}}/rubi_kernel/build
          ls -la ${{runner.workspace}}/rubi_kernel/build
        if: github.event_name == 'create' && github.event['ref_type'] == 'tag'

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
        if: github.event_name == 'create' && github.event['ref_type'] == 'tag'

      - name: Upload Release Asset kernel
        id: upload-release-asset-kernel
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{runner.workspace}}/build/kernel.tar.gz
          asset_name: kernel.tar.gz
          asset_content_type: application/x-tar
        if: github.event_name == 'create' && github.event['ref_type'] == 'tag'

      - name: Upload Release Asset initrd
        id: upload-release-asset-initrd
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{runner.workspace}}/build/initrd_file.tar.gz
          asset_name: initrd_file.tar.gz
          asset_content_type: application/x-tar
        if: github.event_name == 'create' && github.event['ref_type'] == 'tag'

      - name: Upload Release Asset rubiKernel
        id: upload-release-asset-rubiKernel
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{runner.workspace}}/build/rubiKernel.iso.tar.gz
          asset_name: rubiKernel.iso.tar.gz
          asset_content_type: application/x-tar
        if: github.event_name == 'create' && github.event['ref_type'] == 'tag'

      - name: Upload Release Asset grub
        id: upload-release-asset-grub
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{runner.workspace}}/build/grub.iso.tar.gz
          asset_name: grub.iso.tar.gz
          asset_content_type: application/x-tar
        if: github.event_name == 'create' && github.event['ref_type'] == 'tag'
